madlibs = []
answer = input('noun')
madlibs.append(answer)
answer = input('verb')
madlibs.append(answer)
answer = input('adv')
madlibs.append(answer)
answer = input('noun')
madlibs.append(answer)
answer = input('pnoun')
madlibs.append(answer)
answer = input('number')
madlibs.append(answer)
answer = input('state ( in the US)')
madlibs.append(answer)
answer = input('food')
madlibs.append(answer)
answer = input('animal')
madlibs.append(answer)
answer = input('gross thing')
madlibs.append(answer)

print(f"I am a {madlibs[0]} and a {madlibs[1]} very {madlibs[2]} and {madlibs[3]} exploded {madlibs[4]} chicken {madlibs[5]} in {madlibs[6]} while eating {madlibs[7]} and gave some to a {madlibs[8]} and exploded after seeing a {madlibs[9]}")